### ISSUE TITLE
Unable to install GNCam through pod

### ISSUE THREAD

**Issue by jasvindersingh-evon** [gonzalonunez/GNCam#1] opened 2016-10-06 10:14 UTC
I created a new project. And In podfile I added pod 'GNCam' but when trying to install. It is giving an error.

[!] Unable to find a specification for `GNCam`

Please check whats the issue.

**Comment by gonzalonunez** [comment] 2016-10-06 15:10
Hello!

I'm going to take a look at this now. Let me see what's going on!

**Comment by gonzalonunez** [comment] 2016-10-06 15:21
I was not able to reproduce this bug. Here is the podfile that I used:

```
use_frameworks!

target 'GNCam-Test' do
  pod 'GNCam'

  target 'GNCam-TestTests' do
    inherit! :search_paths


  end
end
```

You should **replace** `GNCam-Test` **with** `<YOUR_TARGET_NAME>`, and if you also have unit tests you should **replace** `GNCam-TestTests` **with** `<YOUR_TESTING_TARGET_NAME>`

Let me know if this solves the issue for you! If not, we can keep investigating. Cheers!

**Comment by gonzalonunez** [comment] 2016-10-09 06:03
I'm going to go ahead and close this issue. If you're still facing this problem, please feel free to reopen this issue and I'll take a look! Thanks.

**Closed as completed** 2016-10-09 06:03 UTC
Labels: no repro
